[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "kick"

[[session]]
name = "dotfiles/secrets/scripts"
path = "~/dotfiles/config/secrets/scripts/"
startup_command = "kick"

[[session]]
name = "local"
path = "~/code/platform_work"
startup_command = ""

[[session]]
name = "rest"
path = "~/code/rest"
startup_command = "kick"

[[session]]
name = "wezterm"
path = "~/dotfiles/config/wezterm"
startup_command = "kick wezterm.lua"

[[session]]
name = "aerospace"
path = "~/dotfiles/config"
startup_command = "kick aerospace.toml"

[[session]]
name = "zshrc"
path = "~/dotfiles/config/"
startup_command = "kick .zshrc"

[[session]]
name = "root"
path = "~/"
startup_command = ""

[[session]]
name = "tmux"
path = "~/dotfiles/config/tmux/"
startup_command = "kick tmux.conf"

[[session]]
name = "review"
path = "~/code/platform_work/review/"
startup_command = "ghd"

[[session]]
name = "journal"
path = "~/notes/journal"
startup_command = "./journal.sh"

[[session]]
name = "notes"
path = "~/notes"
startup_command = "kf"

[[session]]
name = "lazy plugins"
path = "~/.local/share/nvim/lazy"
startup_command = "sesh connect $(ls | fzf --ansi --no-border --preview 'glow -s light {}/README.md' --preview-window=right:70,border-none) && exit"

[[session]]
name = "new blog post"
path = "/Users/gkrohn/side/new_blog/src/content/blog"
startup_command = "kick"

[[session]]
name = "neovim test"
path = "~/.config/nvimtest"
startup_command = "kick"

[[session]]
name = "hrkdraft"
path = "/Users/gkrohn/side/pybaseball"
startup_command = "python hr-k-draft.py"

[[session]]
name = "scratch"
path = "~"
startup_command = ""

[[session]]
name = "db"
path = "~"
startup_command = "db"

[[session]]
name = "db_local"
path = "~"
startup_command = "nvim -u ~/.config/nvim/minimal.lua -c ':DadView local'"

[[session]]
name = "db_dev"
path = "~"
startup_command = "nvim -u ~/.config/nvim/minimal.lua -c ':DadView platform_dev'"

[[session]]
name = "db_prod"
path = "~"
startup_command = "nvim -u ~/.config/nvim/minimal.lua -c ':DadView platform_prod'"

[[session]]
name = "ssh tunnels"
path = "~/.ssh"
startup_command = ""

[[session]]
name = "treekanga bare"
path = "~/code/treekanga_work/.bare"
startup_command = "tkt"

[[session]]
name = "platform bare"
path = "~/code/platform_work/.bare"
startup_command = "tkt"

[[session]]
name = "vtop"
path = "~"
startup_command = "vtop"

[[session]]
name = "design docs"
path = "/Users/gkrohn/notes/design_docs"
startup_command = "kick"

[[session]]
name = "daplogs"
path = "/Users/gkrohn/.cache/nvim"
startup_command = "kick dap.log"
