repos:
  offensive-security-platform:
    defaultBranch: development
    worktreeTargetDir: /code/platform_work #assumes starting in the $HOME directory
    zoxideFolders:
      - parent
      - parent/application/src/main/resources/db/migration
      - .github/workflows
      - scan/scanners/containers
      - scan/scan-engine
      - client-ui
      - ui
    postScript: ~/dotfiles/config/scripts/platform_build_script.sh
    bareRepoName: .bare
    autoRunPostScript: false
    tuiTheme: kanagawa
  treekanga:
    defaultBranch: main 
    zoxideFolders:
    worktreeTargetDir: /code/treekanga_work #assumes starting in the $HOME directory
    postScript: ~/dotfiles/config/scripts/test_post_script.sh
    autoRunPostScript: false
    bareRepoName: .bare
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  snap:
    defaultBranch: main 
    zoxideFolders:
    worktreeTargetDir: /code/snap_work #assumes starting in the $HOME directory
    autoRunPostScript: false
    listDisplayMode: directory
    autoPull: true
    tuiTheme: catppuccin-mocha
  attack-surface-management:
    defaultBranch: development
    zoxideFolders:
      - frontend
      - backend
  dgsimgo:
    defaultBranch: main 
  new_ui_platform_work:
    defaultBranch: platform_next_ui
    zoxideFolders:
      - ui
      - parent
      - client-ui
    postScript: ~/dotfiles/config/scripts/platform_build_script.sh
    autoRunPostScript: false
  integration-manager-service:
    defaultBranch: development
    worktreeTargetDir: /code/integration_manager_work
    bareRepoName: .bare

